sudo systemctl disable imu_bosch.service
sudo systemctl disable ip_checker.service
sudo systemctl disable look_ahead.service
sudo systemctl disable mavlink_ajk.service
sudo systemctl disable moving_base.service
sudo systemctl disable qgc_param_command.service
sudo systemctl disable roscore.service
sudo systemctl disable rtk.service
sudo systemctl disable sanyokiki.service
